-- Asignar roles EXACTOS según el JSON original proporcionado

-- Reset all first
UPDATE questions SET roles = null WHERE step_id IN (108,109,110,111,112);

-- Assign exact roles from JSON
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 39;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 40;
UPDATE questions SET roles = '["enfermeria", "medico"]'::jsonb WHERE id = 41;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 42;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 43;
UPDATE questions SET roles = '["medico", "farmacia"]'::jsonb WHERE id = 44;
UPDATE questions SET roles = null WHERE id = 45;
UPDATE questions SET roles = null WHERE id = 46;
UPDATE questions SET roles = '["enfermeria", "farmacia"]'::jsonb WHERE id = 47;
UPDATE questions SET roles = '["farmacia", "enfermeria", "medico"]'::jsonb WHERE id = 48;
UPDATE questions SET roles = '["medico", "farmacia"]'::jsonb WHERE id = 49;
UPDATE questions SET roles = null WHERE id = 50;
UPDATE questions SET roles = null WHERE id = 51;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 52;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 53;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 54;
UPDATE questions SET roles = '["enfermeria", "medico"]'::jsonb WHERE id = 55;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 56;
UPDATE questions SET roles = '["medico", "farmacia"]'::jsonb WHERE id = 57;
UPDATE questions SET roles = '["enfermeria", "farmacia"]'::jsonb WHERE id = 58;
UPDATE questions SET roles = '["enfermeria", "farmacia"]'::jsonb WHERE id = 59;
UPDATE questions SET roles = null WHERE id = 60;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 61;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 62;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 63;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 64;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 65;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 66;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 67;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 68;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 69;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 70;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 71;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 72;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 73;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 74;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 75;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 76;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 77;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 78;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 79;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 80;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 81;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 82;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 83;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 84;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 85;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 86;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 87;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 88;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 89;
UPDATE questions SET roles = '["medico", "farmacia"]'::jsonb WHERE id = 90;
UPDATE questions SET roles = '["farmacia"]'::jsonb WHERE id = 91;
UPDATE questions SET roles = '["medico", "enfermeria", "anestesia"]'::jsonb WHERE id = 96;
UPDATE questions SET roles = '["medico", "anestesia"]'::jsonb WHERE id = 97;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 98;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 99;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 100;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 101;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 102;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 103;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 104;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 105;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 108;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 109;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 110;
UPDATE questions SET roles = '["medico", "enfermeria", "anestesia"]'::jsonb WHERE id = 111;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 112;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 113;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 114;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 115;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 116;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 117;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 118;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 119;
UPDATE questions SET roles = '["anestesia", "farmacia"]'::jsonb WHERE id = 120;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 123;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 124;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 125;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 126;
UPDATE questions SET roles = '["medico", "enfermeria", "anestesia"]'::jsonb WHERE id = 127;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 128;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 129;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 130;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 131;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 132;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 133;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 134;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 135;
UPDATE questions SET roles = '["anestesia", "farmacia"]'::jsonb WHERE id = 136;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 138;
UPDATE questions SET roles = '["anestesia"]'::jsonb WHERE id = 139;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 158;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 159;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 160;
UPDATE questions SET roles = '["enfermeria"]'::jsonb WHERE id = 161;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 305;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 306;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 307;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 308;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 309;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 310;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 311;
UPDATE questions SET roles = '["medico", "enfermeria"]'::jsonb WHERE id = 312;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 313;
UPDATE questions SET roles = '["medico"]'::jsonb WHERE id = 314;
